### ISSUE TITLE
hetzner.hcloud.hcloud_server: 'ServerType' object has no attribute 'architecture'

### ISSUE THREAD

**Issue by knowhy** [ansible-collections/hetzner.hcloud#209]
##### SUMMARY
hetzner.hcloud.hcloud_server fails with `'ServerType' object has no attribute 'architecture'`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
hetzner.hcloud.hcloud_server

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.4]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/rundeck/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/dist-packages/ansible
  ansible collection location = /var/lib/rundeck/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /var/lib/rundeck/.ansible/collections/ansible_collections
Collection     Version
-------------- -------
hetzner.hcloud 1.11.0
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /etc/ansible/ansible.cfg
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 50
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = smart
DEFAULT_HASH_BEHAVIOUR(/etc/ansible/ansible.cfg) = merge
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/etc/ansible/netbox_inventory.yml']
DEFAULT_MANAGED_STR(/etc/ansible/ansible.cfg) = Ansible managed, source: {file}
DEFAULT_PRIVATE_KEY_FILE(/etc/ansible/ansible.cfg) = /var/lib/rundeck/inventory/ansible.pem
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 2
DEPRECATION_WARNINGS(/etc/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = auto_silent
INVENTORY_CACHE_ENABLED(/etc/ansible/ansible.cfg) = True
INVENTORY_CACHE_PLUGIN(/etc/ansible/ansible.cfg) = jsonfile
INVENTORY_CACHE_PLUGIN_CONNECTION(/etc/ansible/ansible.cfg) = /tmp
INVENTORY_CACHE_TIMEOUT(/etc/ansible/ansible.cfg) = 180
TRANSFORM_INVALID_GROUP_CHARS(/etc/ansible/ansible.cfg) = ignore
```

##### STEPS TO REPRODUCE

The `hetzner.hcloud.hcloud_server` module seems broken or documentation needs to be updated since #208 
I get `AttributeError: 'ServerType' object has no attribute 'architecture'` when running the playbook below:

```yaml
---

- hosts: localhost
  tasks:
    - name: Ensure server is present
      hetzner.hcloud.hcloud_server:
        api_token: "..."
        force: false
        image: "debian-11"
        location: "fsn1"
        name: "test"
        server_type: cx11
        state: present
```

##### EXPECTED RESULTS

Task is executed without errors and the hcloud server is created

##### ACTUAL RESULTS

```paste below
TASK [Ensure server is present] ***************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'ServerType' object has no attribute 'architecture'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/var/lib/rundeck/.ansible/tmp/ansible-tmp-1681479703.416523-3259330-178323910119619/AnsiballZ_hcloud_server.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/var/lib/rundeck/.ansible/tmp/ansible-tmp-1681479703.416523-3259330-178323910119619/AnsiballZ_hcloud_server.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/var/lib/rundeck/.ansible/tmp/ansible-tmp-1681479703.416523-3259330-178323910119619/AnsiballZ_hcloud_server.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.hetzner.hcloud.plugins.modules.hcloud_server', init_globals=dict(_module_fqn='ansible_collections.hetzner.hcloud.plugins.modules.hcloud_server', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.9/runpy.py\", line 210, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_hetzner.hcloud.hcloud_server_payload_i6ihikyo/ansible_hetzner.hcloud.hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py\", line 928, in <module>\n  File \"/tmp/ansible_hetzner.hcloud.hcloud_server_payload_i6ihikyo/ansible_hetzner.hcloud.hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py\", line 909, in main\n  File \"/tmp/ansible_hetzner.hcloud.hcloud_server_payload_i6ihikyo/ansible_hetzner.hcloud.hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py\", line 844, in present_server\n  File \"/tmp/ansible_hetzner.hcloud.hcloud_server_payload_i6ihikyo/ansible_hetzner.hcloud.hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py\", line 412, in _create_server\n  File \"/tmp/ansible_hetzner.hcloud.hcloud_server_payload_i6ihikyo/ansible_hetzner.hcloud.hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py\", line 505, in _get_image\n  File \"/usr/local/lib/python3.9/dist-packages/hcloud/core/client.py\", line 117, in __getattr__\n    value = getattr(self.data_model, name)\nAttributeError: 'ServerType' object has no attribute 'architecture'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

**Comment by apricote** [comment]
The new version 1.11.0 of our ansible collection requires version [`v1.19.0`](https://github.com/hetznercloud/hcloud-python/releases/tag/v1.19.0) of hcloud-python, please make sure that is installed.

**Comment by knowhy** [comment]
Ok. Sorry. My bad. I can confirm that the plugin works with hcloud-python v1.19.0
